[formatter.nix]
command = "alejandra"
includes = [ "*.nix" ]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = [ "*.rs" ]

[formatter.markdown]
command = "mdl"
includes = [ "*.md" ]
