[formatter.markdown]
command = "mdl"
includes = [ "*.md" ]
excludes = [
  ".github/pull_request_template.md",
  ".github/ISSUE_TEMPLATE/*.md",
]

[formatter.nix]
command = "alejandra"
includes = [ "*.nix" ]

[formatter.rust]
command = "rustfmt"
options = ["--edition", "2021"]
includes = [ "*.rs" ]
