FROM docker.io/library/rust:bullseye as builder

RUN apt-get update && \
    apt-get install --yes \
      cmake \
      make \
      libhdf5-dev

RUN git clone https://github.com/google/flatbuffers.git && \
    cd flatbuffers && \
    git checkout v22.9.29 && \
    cmake . && \
    make -j flatc && \
    mv flatc /usr/bin

COPY . .
RUN cd stream-to-file && \
    cargo install \
      --path . \
      --root /usr/local

FROM docker.io/library/debian:bullseye-slim

RUN apt-get update && \
    apt-get install --yes \
      libhdf5-103 \
      tini

COPY --from=builder \
  /usr/local/bin/stream-to-file \
  /usr/local/bin/stream-to-file

ENTRYPOINT ["/usr/bin/tini", "--", "/usr/local/bin/stream-to-file"]
