[package]
name = "trace-server"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
leptos.workspace = true
leptos_axum.workspace = true
plotters.workspace = true
rdkafka.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
supermusr-common.workspace = true
supermusr-streaming-types.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true