[package]
name = "trace-server"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", features = ["macros"], optional = true }
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
crossterm.workspace = true
leptos.workspace = true
leptos_actix = { version = "0.6" }
plotters.workspace = true
rdkafka.workspace = true
strum.workspace = true
supermusr-common.workspace = true
supermusr-streaming-types.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[package.metadata.leptos]
# project name
name = "trace-viewer"
bin-package = "server"
lib-package = "front"


[toolchain]
targets = ["wasm32-unknown-unknown"]