[package]
name = "trace-server"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
dioxus = "0.6.3"
dioxus-web = "0.6.3"
actix-files = { version = "0.6", optional = true }
actix-web = { version = "4", features = ["macros"], optional = true }
reqwest = { version = "0.11.18", features = ["json"] }
serde = "1.0.171"
serde_json = "1.0.102"
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
leptos.workspace = true
leptos_actix = { version = "0.6" }
plotters.workspace = true
rdkafka.workspace = true
strum.workspace = true
supermusr-common.workspace = true
supermusr-streaming-types.workspace = true
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true