[package]
name = "satori-integration-tests"
license.workspace = true
version.workspace = true
edition.workspace = true

[dev-dependencies]
# ctor.workspace = true
testing-utils.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
