[package]
name = "trace-archiver-tdengine"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
clap.workspace = true
env_logger.workspace = true
itertools.workspace = true
log.workspace = true
rdkafka.workspace = true
supermusr-common.workspace = true
supermusr-streaming-types.workspace = true
taos.workspace = true
tokio.workspace = true
