---
name: Container Image

on:
  workflow_dispatch:
    inputs:
      ref:
        description: Git ref
        required: true
        type: string
        default: main
      component:
        description: Componenet
        required: true
        type: choice
        options:
          - events-to-histogram
          - frame-assembler
          - simulator
          - stream-to-file
          - trace-to-events
      tags:
        description: Image tags
        required: true
        type: string
        default: latest

jobs:
  container-images:
    name: Build and push container image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: "${{ inputs.ref }}"

      - name: Build container image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: "supermusr-${{ inputs.component }}"
          tags: "${{ inputs.tags }}"
          containerfiles: "./${{ inputs.component }}/Containerfile"
          oci: true

      - name: Push image to GHCR
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ghcr.io/stfc-icd-research-and-design
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
